version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./docker_db:/var/lib/postgresql/data

  app:
    image: node:16
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./todo-list/:/app
    tty: true
